" File managed by Sgoettschkes/dotfiles
" Do not change

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Use pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" Settings for pathogen
syntax on
filetype plugin indent on


" Use solarized
let g:solarized_termcolors=256
set t_Co=16
set background=dark
colorscheme solarized

" Code default settings
set number
set ruler
set laststatus=2
set showcmd
set history=2000

" Search
set hlsearch " Highlight matches
set incsearch " Show first match while still typing
set ignorecase " Does case-insensitive search
set smartcase " Make search behave case-insensitive if only lowercase is entered and case-sensitive if not

" Disable highlight for current search on ESC
" http://stackoverflow.com/questions/657447/vim-clear-last-search-highlighting
nnoremap <esc> :noh<return><esc>

" Tabs
set tabstop=4 
set softtabstop=4
set expandtab
set shiftwidth=4
set autoindent
set showtabline=2

" Prevent cheating
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" Remap leader key
let mapleader=","

" Mapping some leader key settings
noremap <Leader>W :w !sudo tee % > /dev/null

" Use normal bash tab completion for files
set wildmode=longest,list

" Detect .md files as Markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Settings for vimwiki
let g:vimwiki_list = [{'path':'$HOME/workspace/Sgoettschkes/wiki/', 'path_html':'$HOME/workspace/Sgoettschkes/wiki/html/', 'template_path':'$HOME/workspace/Sgoettschkes/wiki/templates/', 'template_default':'def_template', 'template_ext':'.html'}]
