"
" File managed by Sgoettschkes/dotfiles
" Do not change

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Use pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" Settings for pathogen
syntax on
filetype plugin indent on

" Remap leader key
let mapleader=","

" Use solarized
let g:solarized_termcolors=256
set t_Co=16
set background=dark
colorscheme solarized

" Code default settings
set number
set ruler
set laststatus=2
set showcmd
set history=2000 " Store history of commands
set scrolloff=5 " Scroll if the cursor is 5 lines above the bottom
set autowrite " Write files when changing buffers
set colorcolumn=80 "Show vertical line at 80 characters

" Search
set hlsearch " Highlight matches
set incsearch " Show first match while still typing
set ignorecase " Does case-insensitive search
set smartcase " Make search behave better when searching

" Disabe search highlighting with ,e
" http://stackoverflow.com/questions/11940801/mapping-esc-in-vimrc-causes-bizzare-arrow-behaviour
nnoremap <LEADER>e :noh<CR>

" Backup
set backupdir=~/.vim/backup
set dir=~/.vim/temp
set undodir=~/.vim/backup/undo
set undofile
set backup 

" Tabs
set tabstop=4 
set softtabstop=4
set expandtab
set shiftwidth=4
set autoindent
set showtabline=2

" Use normal bash tab completion for files
set wildmode=longest,list

" Prevent cheating
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" Mapping some leader key settings
noremap <Leader>W :w !sudo tee % > /dev/null

" Detect .md files as Markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Settings for vimwiki
let g:vimwiki_list = [{'path':'$HOME/workspace/Sgoettschkes/wiki/', 'path_html':'$HOME/workspace/Sgoettschkes/wiki/html/', 'template_path':'$HOME/workspace/Sgoettschkes/wiki/templates/', 'template_default':'def_template', 'template_ext':'.html'}]
