# File managed by Sgoettschkes/dotfiles
# Do not change

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT='%D %*'

SPACESHIP_EXEC_TIME_ELAPSED=10

SPACESHIP_BATTERY_SHOW=false

SPACESHIP_EXIT_CODE_SHOW=true
