# File managed by Sgoettschkes/dotfiles
# Do not change

# oh-my-zsh configuration
export ZSH=~/.oh-my-zsh
ZSH_THEME="robbyrussell"
ZSH_CUSTOM=~/.dotfiles/zsh/oh-my-zsh-custom

# Plugins
plugins=(asdf brew docker docker-compose git iterm2 mix npm)

source $ZSH/oh-my-zsh.sh

# User configuration

# Add vi keybindings
bindkey -v

# Add asdf path
export ASDF_DATA_DIR=/Users/sebastian/.asdf
path+=$ASDF_DATA_DIR/shims

# Add stack (haskell) path
path+=~/.local/bin/

# Add libpq (PostgreSQL client) path
path+=/opt/homebrew/opt/libpq/bin

# Add escript (mix) path
path+=~/.mix/escripts

if [ -f /Users/sebastian/.docker/init-zsh.sh ]; then
  source /Users/sebastian/.docker/init-zsh.sh # Added by Docker Desktop
fi

# Shopify Hydrogen alias to local projects
alias h2='$(yarn prefix -s)/node_modules/.bin/shopify hydrogen'