# File managed by Sgoettschkes/dotfiles
# Do not change

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

PS1="${debian_chroot:+($debian_chroot)}\[\033[0;32m\]\u@\h\[\033[1;33m\] [\w] $\[\033[00m\] "

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# Using vi keybindings in bash
set -o vi
